<template>
<div>
    <div class="container">
<b-tabs>
  <b-tab title="2017 第八届" active>
    <b-tabs>
        <b-tab title="对垒表与赛果">
           <img src="https://i.imgur.com/3d55v6M.jpg?1" title="第八届亚太辩论赛对垒表" width="70%"/></a>
        </b-tab>
        <b-tab title="最佳辩手">
          <h3>总决赛最佳辩手为新加坡国立大学王肇麟</h3>
          <h3>总决赛人气辩手为新加坡国立大学王肇麟</h3>
          <h3>全场最佳辩手为新加坡国立大学王肇麟</h3>
        </b-tab>
    </b-tabs>
   </b-tab>

  <b-tab title="2015 第七届" >
    <b-tabs>
        <b-tab title="对垒表与赛果">
          <table>
           <tr>
                                        <td>A1:</td>
                                        <td>重庆大学</td>
                                        <td>白璧</td>
                                    </tr>
                                    <tr>
                                        <td>A2:</td>
                                        <td>新加坡国立大学</td>
                                        <td>王肇麟</td>
                                    </tr>
                                    <tr>
                                        <td>A3:</td>
                                        <td>马来西亚理科大学</td>
                                        <td>郑天立</td>
                                    </tr>
                                    <tr>
                                        <td>B1:</td>
                                        <td>莫纳什大学</td>
                                        <td>包江浩</td>
                                    </tr>
                                    <tr>
                                        <td>B2:</td>
                                        <td>马来亚大学</td>
                                        <td>颜如晶</td>
                                    </tr>
                                    <tr>
                                        <td>B3:</td>
                                        <td>新加坡南洋理工大学</td>
                                        <td>陈伟斌</td>
                                    </tr>
                                    <tr>
                                        <td>C1:</td>
                                        <td>香港大学</td>
                                        <td>谭远卓</td>
                                    </tr>
                                    <tr>
                                        <td>C2:</td>
                                        <td>国立中山大学</td>
                                        <td>張凱維</td>
                                    </tr>
                                    <tr>
                                        <td>C3:</td>
                                        <td>澳门大学</td>
                                        <td>鄭博文</td>
                                    </tr>
                                    <tr>
                                        <td>D1:</td>
                                        <td>澳门科技大学</td>
                                        <td>常昊</td>
                                    </tr>
                                    <tr>
                                        <td>D2:</td>
                                        <td>香港浸会大学</td>
                                        <td>陈哲</td>
                                    </tr>
                                    <tr>
                                        <td>D3:</td>
                                        <td>中国政法大学</td>
                                        <td>刘欣东</td>
                                    </tr>
                                    <tr>
                                        <td>循环赛A - 1：</td>
                                        <td>重庆大学</td>
                                        <td>白璧</td>
                                    </tr>
                                    <tr>
                                        <td>循环赛A - 2：</td>
                                        <td>重庆大学</td>
                                        <td>窦蕴康</td>
                                    </tr>
                                    <tr>
                                        <td>循环赛A - 3：</td>
                                        <td>新加坡国立大学</td>
                                        <td>王韵娇</td>
                                    </tr>
                                    <tr>
                                        <td>循环赛B - 1：</td>
                                        <td>马来亚大学</td>
                                        <td>颜如晶</td>
                                    </tr>
                                    <tr>
                                        <td>循环赛B - 2：</td>
                                        <td>新加坡南洋理工大学</td>
                                        <td>陈伟斌</td>
                                    </tr>
                                    <tr>
                                        <td>循环赛B - 3：</td>
                                        <td>马来亚大学</td>
                                        <td>林碧芬</td>
                                    </tr>
                                    <tr>
                                        <td>循环赛C - 1：</td>
                                        <td>国立中山大学</td>
                                        <td>张凯维</td>
                                    </tr>
                                    <tr>
                                        <td>循环赛C - 2：</td>
                                        <td>香港大学</td>
                                        <td>谭远卓</td>
                                    </tr>
                                    <tr>
                                        <td>循环赛C - 3：</td>
                                        <td>国立中山大学</td>
                                        <td>丁启翔</td>
                                    </tr>
                                    <tr>
                                        <td>循环赛D - 1：</td>
                                        <td>金宝拉曼大学</td>
                                        <td>邱志东</td>
                                    </tr>
                                    <tr>
                                        <td>循环赛D - 2：</td>
                                        <td>中国政法大学</td>
                                        <td>刘欣东</td>
                                    </tr>
                                    <tr>
                                        <td>循环赛D - 3：</td>
                                        <td>中国政法大学</td>
                                        <td>刘欣东</td>
                                    </tr>
                                    <tr>
                                        <td>半决赛一：</td>
                                        <td>新加坡国立大学</td>
                                        <td>王韵娇</td>
                                    </tr>
                                    <tr>
                                        <td>半决赛二：</td>
                                        <td>马来亚大学</td>
                                        <td>颜如晶</td>
                                    </tr>
                                    <tr>
                                        <td>季殿赛：</td>
                                        <td>中国政法大学</td>
                                        <td>罗南森</td>
                                    </tr>
                                    <tr>
                                        <td>总决赛：</td>
                                        <td>马来亚大学</td>
                                        <td>颜如晶</td>
                                    </tr>
                                  </table>
        </b-tab>
        <b-tab title="最佳辩手">
          <table>
            <tr>
                                        <td>全场最佳辩手：</td>
                                        <td>马来亚大学</td>
                                        <td>颜如晶</td>
                                    </tr>
          </table>
        </b-tab>
    </b-tabs>
    </b-tab>

  <b-tab title="2013 第六届" >
    <b-tabs>
        <b-tab title="对垒表与赛果">
          <table>
            <tr>
                                        <td>初赛一：</td>
                                        <td>（正）世界文化遗产应该商业化</td>
                                        <td>墨尔本大学</td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）世界文化遗产不应该商业化</td>
                                        <td><strong>中央民族大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>初赛二：</td>
                                        <td>（正）物资资助比人力资助更能协助落后国家的发展</td>
                                        <td><strong>新加坡国立大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）人力资助比物资资助更能协助落后国家的发展</td>
                                        <td>香港大学</td>
                                    </tr>
                                    <tr>
                                        <td>初赛三：</td>
                                        <td>（正）大学教育应更注重硬体设施</td>
                                        <td>澳门科技大学</td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）大学教育应更注重软体设施</td>
                                        <td><strong>马来西亚国油大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>初赛四：</td>
                                        <td>（正）各国政府应该立法规定子女履行赡养父母的责任</td>
                                        <td><strong>台湾大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）各国政府不应该立法规定子女履行赡养父母的责任</td>
                                        <td>电子科技大学</td>
                                    </tr>
                                    <tr>
                                        <td>初赛五：</td>
                                        <td>（正）社交网站拉近了人与人之间的距离</td>
                                        <td><strong>台湾世新大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）社交网站疏远了人与人之间的距离</td>
                                        <td>马来西亚国民大学</td>
                                    </tr>
                                    <tr>
                                        <td>初赛六：</td>
                                        <td>（正）单一货币政策对欧元国家利大于弊</td>
                                        <td>香港城市大学</td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）单一货币政策对欧元国家弊大于利</td>
                                        <td><strong>重庆大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>初赛七：</td>
                                        <td>（正）崇洋媚外是本土文化流失的主要原因</td>
                                        <td><strong>莫纳什大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）崇洋媚外不是本土文化流失的主要原因</td>
                                        <td>清华大学</td>
                                    </tr>
                                    <tr>
                                        <td>初赛八：</td>
                                        <td>（正）奖励生育有助于提高生育率</td>
                                        <td><strong>新加坡南洋理工大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）奖励生育无助于提高生育率</td>
                                        <td>澳门大学</td>
                                    </tr>
                                    <tr>
                                        <td>复赛一：</td>
                                        <td>（正）表露自我情感比收藏自我情感更利于人际交往</td>
                                        <td><strong>中央民族大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）收藏自我情感比表露自我情感更利于人际交往</td>
                                        <td>新加坡国立大学</td>
                                    </tr>
                                    <tr>
                                        <td>复赛二：</td>
                                        <td>（正）个人英雄主义适合于21世纪</td>
                                        <td>马来西亚国油大学</td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）个人英雄主义不适合于21世纪</td>
                                        <td><strong>台湾大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>复赛三：</td>
                                        <td>（正）年龄差距是爱情的绊脚石</td>
                                        <td>台湾世新大学</td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）年龄差距不是爱情的绊脚石</td>
                                        <td><strong>重庆大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>复赛四：</td>
                                        <td>（正）创意需要教育的养成</td>
                                        <td><strong>莫纳什大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）创意不需要教育的养成</td>
                                        <td>新加坡南洋理工大学</td>
                                    </tr>
                                    <tr>
                                        <td>半决赛一：</td>
                                        <td>（正）人类的精神文明随着科技发展而进步</td>
                                        <td><strong>中央民族大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）人类的精神文明不随着科技发展而进步</td>
                                        <td>台湾大学</td>
                                    </tr>
                                    <tr>
                                        <td>半决赛二：</td>
                                        <td>（正）韬光隐晦才是现今社会的生存之道</td>
                                        <td>重庆大学</td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）锋芒毕露才是现今社会的生存之道</td>
                                        <td><strong>莫纳什大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>决赛：</td>
                                        <td>（正）社会媒体是社会民主化的重要推手</td>
                                        <td>中央民族大学</td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）社会媒体不是社会民主化的重要推手</td>
                                        <td><strong>莫纳什大学</strong></td>
                                    </tr>
           </table>
         </b-tab>
        <b-tab title="最佳辩手">
          <table>
            <tr>
                                        <td colspan="2"><strong>最佳辩手</strong></td>
                                        <td>&nbsp;</td>
                                    </tr>
                                    <tr>
                                        <td>初赛一：</td>
                                        <td>墨尔本大学</td>
                                        <td>王志享</td>
                                    </tr>
                                    <tr>
                                        <td>初赛二：</td>
                                        <td>新加坡国立大学</td>
                                        <td>张核</td>
                                    </tr>
                                    <tr>
                                        <td>初赛三：</td>
                                        <td>马来西亚国油大学</td>
                                        <td>郑亿德</td>
                                    </tr>
                                    <tr>
                                        <td>初赛四：</td>
                                        <td>台湾大学</td>
                                        <td>郭智安</td>
                                    </tr>
                                    <tr>
                                        <td>初赛五：</td>
                                        <td>台湾世新大学</td>
                                        <td>张正忻</td>
                                    </tr>
                                    <tr>
                                        <td>初赛六：</td>
                                        <td>重庆大学</td>
                                        <td>周维</td>
                                    </tr>
                                    <tr>
                                        <td>初赛七：</td>
                                        <td>清华大学</td>
                                        <td>冯若谷</td>
                                    </tr>
                                    <tr>
                                        <td>初赛八：</td>
                                        <td>新加坡南洋理工大学</td>
                                        <td>钟诏航</td>
                                    </tr>
                                    <tr>
                                        <td>复赛一：</td>
                                        <td>新加坡国立大学</td>
                                        <td>王韵娇</td>
                                    </tr>
                                    <tr>
                                        <td>复赛二：</td>
                                        <td>台湾大学</td>
                                        <td>郭智安</td>
                                    </tr>
                                    <tr>
                                        <td>复赛三：</td>
                                        <td>台湾世新大学</td>
                                        <td>黄甦俞</td>
                                    </tr>
                                    <tr>
                                        <td>复赛四：</td>
                                        <td>莫纳什大学</td>
                                        <td>包江浩</td>
                                    </tr>
                                    <tr>
                                        <td>半决赛一：</td>
                                        <td>台湾大学</td>
                                        <td>郭智安</td>
                                    </tr>
                                    <tr>
                                        <td>半决赛二：</td>
                                        <td>莫纳什大学</td>
                                        <td>李挺</td>
                                    </tr>
                                    <tr>
                                        <td>决赛：</td>
                                        <td>莫纳什大学</td>
                                        <td>李挺</td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>&nbsp;</td>
                                        <td>&nbsp;</td>
                                    </tr>
                                    <tr>
                                        <td>全场最佳辩手：</td>
                                        <td>台湾大学</td>
                                        <td>郭智安</td>
                                    </tr>
           </table>
        </b-tab>
    </b-tabs>
    </b-tab>

  <b-tab title="2011 第五届" >
    <b-tabs>
        <b-tab title="对垒表与赛果">
          <table>
            <tr>
                                        <td>初赛一：</td>
                                        <td>（正）知识分子是社会进步的必要条件</td>
                                        <td>悉尼大学</td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）知识分子不是社会进步的必要条件</td>
                                        <td><strong>厦门大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>初赛二：</td>
                                        <td>（正）修复历史遗迹有助于保留人类的历史记忆</td>
                                        <td>澳门科技大学</td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）修复历史遗迹无助于保留人类的历史记忆</td>
                                        <td><strong>新加坡南洋理工大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>初赛三：</td>
                                        <td>（正）法律与人情并不相悖</td>
                                        <td><strong>马来西亚多媒体大学（赛城院校）</strong></td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）法律与人情有所相悖</td>
                                        <td>香港浸会大学</td>
                                    </tr>
                                    <tr>
                                        <td>初赛四：</td>
                                        <td>（正）政府应该实行最低工资的制度</td>
                                        <td>北京中医药大学</td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）政府不应该实行最低工资的制度</td>
                                        <td><strong>台湾东吴大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>初赛五：</td>
                                        <td>（正）同化政策有利于国民团结</td>
                                        <td>新加坡国立大学</td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）同化政策不利于国民团结</td>
                                        <td><strong>墨尔本大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>初赛六：</td>
                                        <td>（正）网络语言有利于语言的发展</td>
                                        <td>台湾国立政治大学</td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）网络语言不利于语言的发展</td>
                                        <td><strong>香港大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>初赛七：</td>
                                        <td>（正）新闻自由是民主化的必要条件</td>
                                        <td><strong>澳门大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）新闻自由不是民主化的必要条件</td>
                                        <td>香港中文大学</td>
                                    </tr>
                                    <tr>
                                        <td>初赛八：</td>
                                        <td>（正）政府是推广环保的火车头</td>
                                        <td>马拉西亚苏丹伊德里斯教育大学</td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）政府不是推广环保的火车头</td>
                                        <td><strong>北京交通大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>复赛一：</td>
                                        <td>（正）整容能让人找回信心</td>
                                        <td>厦门大学</td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）整容不能让人找回信心</td>
                                        <td><strong>新加坡南洋理工大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>复赛二：</td>
                                        <td>（正）处世圆通是人在社会上重要的生存法则</td>
                                        <td>&nbsp;马来西亚多媒体大学（赛城院校）</td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）处世圆通不是人在社会上重要的生存法则</td>
                                        <td><strong>台湾东吴大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>复赛三：</td>
                                        <td>（正）远距离是爱情的杀手</td>
                                        <td>墨尔本大学</td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）远距离不是爱情的杀手</td>
                                        <td><strong>香港大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>复赛四：</td>
                                        <td>（正）贪婪是人的本性使然</td>
                                        <td><strong>澳门大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）贪婪不是人的本性使然</td>
                                        <td>北京交通大学</td>
                                    </tr>
                                    <tr>
                                        <td>半决赛一：</td>
                                        <td>（正）当代社会需要明星</td>
                                        <td><strong>新加坡南洋理工大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）当代社会不需要明星</td>
                                        <td>东吴大学</td>
                                    </tr>
                                    <tr>
                                        <td>半决赛二：</td>
                                        <td>（正）自由竞争能有效遏制市场垄断</td>
                                        <td>香港大学</td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）自由竞争不能有效遏制市场垄断</td>
                                        <td><strong>澳门大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>决赛：</td>
                                        <td>（正）全球化扩大世界各国的贫富差距</td>
                                        <td>新加坡南洋理工大学</td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）全球化缩小世界各国的贫富差距</td>
                                        <td><strong>澳门大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td colspan="2"><strong>最佳辩手</strong></td>
                                        <td>&nbsp;</td>
                                    </tr>
                                    <tr>
                                        <td>初赛一：</td>
                                        <td>厦门大学</td>
                                        <td>李龙</td>
                                    </tr>
                                    <tr>
                                        <td>初赛二：</td>
                                        <td>新加坡南洋理工大学</td>
                                        <td>于剑琪</td>
                                    </tr>
                                    <tr>
                                        <td>初赛三：</td>
                                        <td>香港浸会大学</td>
                                        <td>关导</td>
                                    </tr>
                                    <tr>
                                        <td>初赛四：</td>
                                        <td>北京中医药大学</td>
                                        <td>尹航</td>
                                    </tr>
                                    <tr>
                                        <td>初赛五：</td>
                                        <td>新加坡国立大学</td>
                                        <td>庞颖</td>
                                    </tr>
                                    <tr>
                                        <td>初赛六：</td>
                                        <td>香港大学</td>
                                        <td>封启云</td>
                                    </tr>
                                    <tr>
                                        <td>初赛七：</td>
                                        <td>澳门大学</td>
                                        <td>姚兆华</td>
                                    </tr>
                                    <tr>
                                        <td>初赛八：</td>
                                        <td>马拉西亚苏丹伊德里斯教育大学</td>
                                        <td>张康文</td>
                                    </tr>
                                    <tr>
                                        <td>复赛一：</td>
                                        <td>新加坡南洋理工大学</td>
                                        <td>于剑琪</td>
                                    </tr>
                                    <tr>
                                        <td>复赛二：</td>
                                        <td>台湾东吴大学</td>
                                        <td>邱仁颉</td>
                                    </tr>
                                    <tr>
                                        <td>复赛三：</td>
                                        <td>香港大学</td>
                                        <td>封启云</td>
                                    </tr>
                                    <tr>
                                        <td>复赛四：</td>
                                        <td>澳门大学</td>
                                        <td>姚兆华</td>
                                    </tr>
                                    <tr>
                                        <td>半决赛一：</td>
                                        <td>东吴大学</td>
                                        <td>邱仁颉</td>
                                    </tr>
                                    <tr>
                                        <td>半决赛二：</td>
                                        <td>香港大学</td>
                                        <td>狄一</td>
                                    </tr>
                                    <tr>
                                        <td>决赛：</td>
                                        <td>澳门大学</td>
                                        <td>姚兆华</td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>&nbsp;</td>
                                        <td>&nbsp;</td>
                                    </tr>

          </table>
         </b-tab>
        <b-tab title="最佳辩手">
          <table>
            <tr>
                                        <td>全场最佳辩手：</td>
                                        <td>澳门大学</td>
                                        <td>姚兆华</td>
                                    </tr>
          </table>
         </b-tab>
    </b-tabs>
   </b-tab>

  <b-tab title="2008 第四届" >
    <b-tabs>
        <b-tab title="对垒表与赛果">
        <table>
          <tr>
                                                  <td>初赛一：</td>
                                                  <td>（正）发展中国家强化版权保护利大于弊</td>
                                                  <td>多媒体大学（马六甲园区）</td>
                                              </tr>
                                              <tr>
                                                  <td>&nbsp;</td>
                                                  <td>（反）发展中国家强化版权保护弊大于利</td>
                                                  <td><strong>中国北京交通大学</strong></td>
                                              </tr>
                                              <tr>
                                                  <td>初赛二：</td>
                                                  <td>（正）自由贸易比保护贸易有利国家发展</td>
                                                  <td><strong>中国上海交通大学</strong></td>
                                              </tr>
                                              <tr>
                                                  <td>&nbsp;</td>
                                                  <td>（反）保护贸易比自由贸易有利国家发展</td>
                                                  <td>马来亚科技大学</td>
                                              </tr>
                                              <tr>
                                                  <td>初赛三：</td>
                                                  <td>（正）社会安定靠温饱多于道德</td>
                                                  <td>澳门理工学院</td>
                                              </tr>
                                              <tr>
                                                  <td>&nbsp;</td>
                                                  <td>（反）社会安定靠道德多于温饱</td>
                                                  <td><strong>澳门大学</strong></td>
                                              </tr>
                                              <tr>
                                                  <td>初赛四：</td>
                                                  <td>（正）竞争在教育里是必要的</td>
                                                  <td><strong>马来西亚博特拉大学</strong></td>
                                              </tr>
                                              <tr>
                                                  <td>&nbsp;</td>
                                                  <td>（反）竞争在教育里不是必要的</td>
                                                  <td>新加坡国立大学</td>
                                              </tr>
                                              <tr>
                                                  <td>初赛五：</td>
                                                  <td>（正）制裁国家有助于维护世界和平</td>
                                                  <td>莫斯科国立大学</td>
                                              </tr>
                                              <tr>
                                                  <td>&nbsp;</td>
                                                  <td>（反）制裁国家无助于维护世界和平</td>
                                                  <td><strong>澳大利亚墨尔本大学</strong></td>
                                              </tr>
                                              <tr>
                                                  <td>初赛六：</td>
                                                  <td>（正）科技进步让地球变大</td>
                                                  <td><strong>香港浸会大学</strong></td>
                                              </tr>
                                              <tr>
                                                  <td>&nbsp;</td>
                                                  <td>（反）科技进步让地球变小</td>
                                                  <td>新加坡南洋理工大学</td>
                                              </tr>
                                              <tr>
                                                  <td>初赛七：</td>
                                                  <td>（正）现代人应锋芒毕露</td>
                                                  <td>马来亚大学</td>
                                              </tr>
                                              <tr>
                                                  <td>&nbsp;</td>
                                                  <td>（反）现代人应韬光养晦</td>
                                                  <td><strong>香港大学</strong></td>
                                              </tr>
                                              <tr>
                                                  <td>初赛八：</td>
                                                  <td>（正）知足应是人类应有的处世态度</td>
                                                  <td><strong>台湾世新大学</strong></td>
                                              </tr>
                                              <tr>
                                                  <td>&nbsp;</td>
                                                  <td>（反）知足不应是人类应有的处世态度</td>
                                                  <td>台湾东吴大学</td>
                                              </tr>
                                              <tr>
                                                  <td>复赛一：</td>
                                                  <td>（正）奥运有利于国家经济发展</td>
                                                  <td>中国北京交通大学</td>
                                              </tr>
                                              <tr>
                                                  <td>&nbsp;</td>
                                                  <td>（反）奥运不利于国家经济发展</td>
                                                  <td><strong>中国上海交通大学</strong></td>
                                              </tr>
                                              <tr>
                                                  <td>复赛二：</td>
                                                  <td>（正）行成于思</td>
                                                  <td>澳门大学</td>
                                              </tr>
                                              <tr>
                                                  <td>&nbsp;</td>
                                                  <td>（反）思成于行</td>
                                                  <td><strong>马来西亚博特拉大学</strong></td>
                                              </tr>
                                              <tr>
                                                  <td>复赛三：</td>
                                                  <td>（正）东施应该整容</td>
                                                  <td><strong>澳大利亚墨尔本大学</strong></td>
                                              </tr>
                                              <tr>
                                                  <td>&nbsp;</td>
                                                  <td>（反）东施不应该整容</td>
                                                  <td>香港浸会大学</td>
                                              </tr>
                                              <tr>
                                                  <td>复赛四：</td>
                                                  <td>（正）宽收严试，是用人良法</td>
                                                  <td><strong>香港大学</strong></td>
                                              </tr>
                                              <tr>
                                                  <td>&nbsp;</td>
                                                  <td>（反）严收宽试，是用人良法</td>
                                                  <td>台湾世新大学</td>
                                              </tr>
                                              <tr>
                                                  <td>半决赛一：</td>
                                                  <td>（正）精神出轨才是不忠的表现</td>
                                                  <td><strong>中国上海交通大学</strong></td>
                                              </tr>
                                              <tr>
                                                  <td>&nbsp;</td>
                                                  <td>（反）肉体出轨才是不忠的表现</td>
                                                  <td>马来西亚博特拉大学</td>
                                              </tr>
                                              <tr>
                                                  <td>半决赛二：</td>
                                                  <td>（正）电影制作应该以艺术价值为导向</td>
                                                  <td>澳大利亚墨尔本大学</td>
                                              </tr>
                                              <tr>
                                                  <td>&nbsp;</td>
                                                  <td>（反）电影制作应该以大众需求为导向</td>
                                                  <td><strong>香港大学</strong></td>
                                              </tr>
                                              <tr>
                                                  <td>决赛：</td>
                                                  <td>（正）依靠人类醒觉能最有效减缓全球暖化现象</td>
                                                  <td>中国上海交通大学</td>
                                              </tr>
                                              <tr>
                                                  <td>&nbsp;</td>
                                                  <td>（反）依靠国际立法能最有效减缓全球暖化现象</td>
                                                  <td><strong>香港大学</strong></td>
                                              </tr>
        </table></b-tab>
        <b-tab title="最佳辩手">
        <table>
          <tr>
                                        <td>初赛一：</td>
                                        <td>中国北京交通大学</td>
                                        <td>管科</td>
                                    </tr>
                                    <tr>
                                        <td>初赛二：</td>
                                        <td>马来亚科技大学</td>
                                        <td>邱志文</td>
                                    </tr>
                                    <tr>
                                        <td>初赛三：</td>
                                        <td>澳门大学</td>
                                        <td>陈思渊</td>
                                    </tr>
                                    <tr>
                                        <td>初赛四：</td>
                                        <td>新加坡国立大学</td>
                                        <td>任重远</td>
                                    </tr>
                                    <tr>
                                        <td>初赛五：</td>
                                        <td>澳大利亚墨尔本大学</td>
                                        <td>陆孝初</td>
                                    </tr>
                                    <tr>
                                        <td>初赛六：</td>
                                        <td>香港浸会大学</td>
                                        <td>许之葭</td>
                                    </tr>
                                    <tr>
                                        <td>初赛七：</td>
                                        <td>香港大学</td>
                                        <td>刘桢</td>
                                    </tr>
                                    <tr>
                                        <td>初赛八：</td>
                                        <td>台湾东吴大学</td>
                                        <td>张哲耀</td>
                                    </tr>
                                    <tr>
                                        <td>复赛一：</td>
                                        <td>中国北京交通大学</td>
                                        <td>管科</td>
                                    </tr>
                                    <tr>
                                        <td>复赛二：</td>
                                        <td>澳门大学</td>
                                        <td>陈思渊</td>
                                    </tr>
        </table></b-tab>
    </b-tabs>
   </b-tab>

  <b-tab title="2007 第三届" >
    <br/>

    <center> <h4>台湾中华辩论人交流协会于2007年成功在台湾轮办第三届亚太大专华语辩论公开赛。<br>此项比赛的赛果并未保留下来。</h4></center>
   </b-tab>

  <b-tab title="2006 第二届" >
    <b-tabs>
        <b-tab title="对垒表与赛果">
          <table>
                                      <tr>
                                      <td>初赛一：</td>
                                      <td>(正) &nbsp; 减肥瘦身主要出于人们对美的追求</td>
                                      <td>香港中文大学</td>
                                  </tr>
                                  <tr>
                                      <td>&nbsp;</td>
                                      <td>(反) 减肥瘦身主要出于人们对健康的追求</td>
                                      <td><strong>俄罗斯莫斯科国立大学</strong></td>
                                  </tr>
                                  <tr>
                                      <td>初赛二：</td>
                                      <td>(正) 平凡是福</td>
                                      <td>台湾国立政治大学</td>
                                  </tr>
                                  <tr>
                                      <td>&nbsp;</td>
                                      <td>(反) 平凡不是福</td>
                                      <td><strong>新加坡国立大学</strong></td>
                                  </tr>
                                  <tr>
                                      <td>初赛三：</td>
                                      <td>(正) 同性婚姻应该合法化</td>
                                      <td>澳门科技大学</td>
                                  </tr>
                                  <tr>
                                      <td>&nbsp;</td>
                                      <td>(反) 同性婚姻不应该合法化</td>
                                      <td><strong>马来亚大学</strong></td>
                                  </tr>
                                  <tr>
                                      <td>初赛四：</td>
                                      <td>(正) 新闻自由对社会稳定利大于弊</td>
                                      <td>澳洲新南威尔斯大学</td>
                                  </tr>
                                  <tr>
                                      <td>&nbsp;</td>
                                      <td>(反) 新闻自由对社会稳定弊大于利</td>
                                      <td><strong>中国暨南大学</strong></td>
                                  </tr>
                                  <tr>
                                      <td>初赛五：</td>
                                      <td>(正) 选择越多越幸福</td>
                                      <td>中国福建师范大学</td>
                                  </tr>
                                  <tr>
                                      <td>&nbsp;</td>
                                      <td>(反) 选择越多越痛苦</td>
                                      <td><strong>新加坡南洋理工大学</strong></td>
                                  </tr>
                                  <tr>
                                      <td>初赛六：</td>
                                      <td>(正) 以爱情为基础的婚姻比较稳定</td>
                                      <td><strong>马来西亚国能大学</strong></td>
                                  </tr>
                                  <tr>
                                      <td>&nbsp;</td>
                                      <td>(反) 以面包为基础的婚姻比较稳定</td>
                                      <td>澳洲墨尔本大学</td>
                                  </tr>
                                  <tr>
                                      <td>初赛七：</td>
                                      <td>(正) 化学去势是对付强暴犯的有效途径</td>
                                      <td>澳门大学</td>
                                  </tr>
                                  <tr>
                                      <td>&nbsp;</td>
                                      <td>(反) 化学去势不是对付强暴犯的有效途径</td>
                                      <td><strong>台湾世新大学</strong></td>
                                  </tr>
                                  <tr>
                                      <td>初赛八：</td>
                                      <td>(正) 父母应让儿童提早适应社会</td>
                                      <td><strong>台湾东吴大学</strong></td>
                                  </tr>
                                  <tr>
                                      <td>&nbsp;</td>
                                      <td>(反) 父母应让儿童保留童真</td>
                                      <td>澳门理工学院</td>
                                  </tr>
                                  <tr>
                                      <td>复赛一：</td>
                                      <td>(正) 人权高于国家安全</td>
                                      <td>俄罗斯莫斯科国立大学</td>
                                  </tr>
                                  <tr>
                                      <td>&nbsp;</td>
                                      <td>(反) 国家安全高于人权</td>
                                      <td><strong>新加坡国立大学</strong></td>
                                  </tr>
                                  <tr>
                                      <td>复赛二：</td>
                                      <td>(正) 相似性格使爱情更持久</td>
                                      <td><strong>马来亚大学</strong></td>
                                  </tr>
                                  <tr>
                                      <td>&nbsp;</td>
                                      <td>(反) 互补性格使爱情更持久</td>
                                      <td>中国暨南大学</td>
                                  </tr>
                                  <tr>
                                      <td>复赛三：</td>
                                      <td>(正) 买卖人体器官应该合法化</td>
                                      <td>新加坡南洋理工大学</td>
                                  </tr>
                                  <tr>
                                      <td>&nbsp;</td>
                                      <td>(反) 买卖人体器官不应该合法化</td>
                                      <td><strong>马来西亚国能大学</strong></td>
                                  </tr>
                                  <tr>
                                      <td>复赛四：</td>
                                      <td>(正) 效果是评价行为善恶的标准</td>
                                      <td><strong>台湾世新大学</strong></td>
                                  </tr>
                                  <tr>
                                      <td>&nbsp;</td>
                                      <td>(反) 动机是评价行为善恶的标准</td>
                                      <td>台湾东吴大学</td>
                                  </tr>
                                  <tr>
                                      <td>半决赛一：</td>
                                      <td>(正) 现代人应效法太公钓鱼</td>
                                      <td>&nbsp;<strong>新加坡国立大学</strong></td>
                                  </tr>
                                  <tr>
                                      <td>&nbsp;</td>
                                      <td>(反) 现代人应效法毛遂自荐</td>
                                      <td>马来亚大学</td>
                                  </tr>
                                  <tr>
                                      <td>半决赛二：</td>
                                      <td>(正) 全球化下，学外语比学母语重要</td>
                                      <td>&nbsp;<strong>马来西亚国能大学</strong></td>
                                  </tr>
                                  <tr>
                                      <td>&nbsp;</td>
                                      <td>(反) 全球化下，学母语比学外语重要</td>
                                      <td>台湾世新大学</td>
                                  </tr>
                                  <tr>
                                      <td>决赛：</td>
                                      <td>(正) 反恐战争使世界更安全</td>
                                      <td><strong>新加坡国立大学</strong></td>
                                  </tr>
                                  <tr>
                                      <td>&nbsp;</td>
                                      <td>(反) 反恐战争使世界更危险</td>
                                      <td>马来西亚国能大学</td>
                                  </tr>
                                </table>
        </b-tab>
        <b-tab title="最佳辩手">
          <table>

                                    <tr>
                                          <td>决赛：</td>
                                          <td>马来西亚国能大学</td>
                                          <td>颜江翰</td>
                                      </tr>
                                    </table>
                </b-tab>
    </b-tabs>
   </b-tab>

  <b-tab title="2004 第一届" >
    <b-tabs>
        <b-tab title="对垒表与赛果">
          <table>
                                    <tr>
                                        <td>初赛一：</td>
                                        <td>（正）长生不老是人类的福音</td>
                                        <td>中国上海大学</td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）长生不老不是人类的福音</td>
                                        <td><strong>新加坡国立大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>初赛二：</td>
                                        <td>（正）未来时代知识将驾驭资本</td>
                                        <td>马来西亚博特拉大学</td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）未来时代资本将驾驭知识</td>
                                        <td><strong>台湾世新大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>初赛三：</td>
                                        <td>（正）体育明星偶像化有利于体育发展</td>
                                        <td>澳洲墨尔本大学</td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）体育明星偶像化不利于体育发展</td>
                                        <td><strong>澳门大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>初赛四：</td>
                                        <td>（正）娱乐节目充斥荧幕是文化的进步</td>
                                        <td>马来西亚精英学院</td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）娱乐节目充斥荧幕是文化的退步</td>
                                        <td><strong>香港浸会大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>初赛五：</td>
                                        <td>（正）全球化会使人们丧失自己的本土性</td>
                                        <td><strong>台湾辅仁大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）全球化不会使人们丧失自己的本土性</td>
                                        <td>澳门科技大学</td>
                                    </tr>
                                    <tr>
                                        <td>初赛六：</td>
                                        <td>（正）乱世中，人们应有宁为玉碎，不为瓦全的精神</td>
                                        <td>马来西亚北方大学</td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）乱世中，人们应有留得青山在，不怕没柴烧的思想</td>
                                        <td><strong>新加坡南洋理工大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>初赛七：</td>
                                        <td>（正）纪律促进个性的发展</td>
                                        <td>香港大学</td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）纪律限制个性的发展</td>
                                        <td><strong>中国暨南大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>初赛八：</td>
                                        <td>（正）发展经济应鼓励超前消费</td>
                                        <td><strong>台湾东吴大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）发展经济不应鼓励超前消费</td>
                                        <td>马来西亚国能大学</td>
                                    </tr>
                                    <tr>
                                        <td>复赛一：</td>
                                        <td>（正）企业专业化比多元化有利</td>
                                        <td><strong>新加坡国立大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）企业多元化比专业化有利</td>
                                        <td>台湾世新大学</td>
                                    </tr>
                                    <tr>
                                        <td>复赛二：</td>
                                        <td>（正）人际关系比真才实学重要</td>
                                        <td><strong>澳门大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）真才实学比人际关系重要</td>
                                        <td>香港浸会大学</td>
                                    </tr>
                                    <tr>
                                        <td>复赛三：</td>
                                        <td>（正）知识积累比知识创新更重要</td>
                                        <td><strong>台湾辅仁大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）知识创新并知识积累更重要</td>
                                        <td>新加坡南洋理工大学</td>
                                    </tr>
                                    <tr>
                                        <td>复赛四：</td>
                                        <td>（正）价值理性比工具理性更值得提倡</td>
                                        <td>中国暨南大学</td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）工具理性比价值理性更值得提倡</td>
                                        <td><strong>台湾东吴大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>半决赛一：</td>
                                        <td>（正）新闻市场价值比新闻道德重要</td>
                                        <td>新加坡国立大学</td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）新闻道德比新闻市场价值重要</td>
                                        <td><strong>澳门大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>半决赛二：</td>
                                        <td>（正）骑驴找马的爱情观可能找到真爱</td>
                                        <td><strong>台湾辅仁大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）骑驴找马的爱情观不可能找到真爱</td>
                                        <td>台湾东吴大学</td>
                                    </tr>
                                    <tr>
                                        <td>决赛：</td>
                                        <td>（正）科技发展应有伦理界限</td>
                                        <td><strong>澳门大学</strong></td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>（反）科技发展不应有伦理界限</td>
                                        <td>台湾辅仁大学</td>
                                    </tr>
                                  </table>
          </b-tab>
        <b-tab title="最佳辩手">
          <table>
          <tr>
              <td>初赛一：</td>
              <td>新加坡国立大学</td>
              <td>刘易杰</td>
          </tr>
          <tr>
              <td>初赛二：</td>
              <td>台湾世新大学</td>
              <td>黄执中</td>
          </tr>
          <tr>
              <td>初赛三：</td>
              <td>澳门大学</td>
              <td>倪明</td>
          </tr>
          <tr>
              <td>初赛四：</td>
              <td>香港浸会大学</td>
              <td>徐素洁</td>
          </tr>
          <tr>
              <td>初赛五：</td>
              <td>台湾辅仁大学</td>
              <td>陈思渊</td>
          </tr>
          <tr>
              <td>初赛六：</td>
              <td>新加坡南洋理工大学</td>
              <td>尚磊</td>
          </tr>
          <tr>
              <td>初赛七：</td>
              <td>中国暨南大学</td>
              <td>汤耐冬</td>
          </tr>
          <tr>
              <td>初赛八：</td>
              <td>台湾东吴大学</td>
              <td>范凯云</td>
          </tr>
          <tr>
              <td>复赛一：</td>
              <td>台湾世新大学</td>
              <td>黄执中</td>
          </tr>
          <tr>
              <td>复赛二：</td>
              <td>澳门大学</td>
              <td>刘京京</td>
          </tr>
          <tr>
              <td>复赛三：</td>
              <td>台湾辅仁大学</td>
              <td>陈思渊</td>
          </tr>
          <tr>
              <td>复赛四：</td>
              <td>台湾东吴大学</td>
              <td>温朗东</td>
          </tr>
          <tr>
              <td>半决赛一：</td>
              <td>澳门大学</td>
              <td>倪明</td>
          </tr>
          <tr>
              <td>半决赛二：</td>
              <td>台湾辅仁大学</td>
              <td>陈思渊</td>
          </tr>
          <tr>
              <td>决赛：</td>
              <td>澳门大学</td>
              <td>倪明</td>
          </tr>
          <tr>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
          </tr>
          <tr>
              <td>全场最佳辩手：</td>
              <td>澳门大学</td>
              <td>倪明</td>
          </tr>
        </table>
        </b-tab>
    </b-tabs>
   </b-tab>

</b-tabs>
</div>
</div>
</template>
<script>


export default{
name:'pastyear',
}
</script>
<style scoped>
    .container{background-color: #F7F7F7;
        padding: 20px 25px 30px;
        margin: 0 auto 25px;
        margin-top: 50px;
        /* shadows and rounded borders */
        -moz-border-radius: 20px;
        -webkit-border-radius: 20px;
        border-radius: 20px;
        -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        width:100%;}
    ul{list-style:square;}
</style>
